services:
  - type: web
    name: job-portal-backend
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://palbhupendra555:bhupendrajs98@cluster0.rlznbgy.mongodb.net/?appName=Cluster0"
      - key: PORT
        value: "9265"
      - key: JWT_SECRET
        value: "job_portal_super_secret_key_9265"
